Resources:
  CICDVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16      

  IGW:
    Type: AWS::EC2::InternetGateway

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CICDVPC
      InternetGatewayId: !Ref IGW

  PubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CICDVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "ap-south-1b"
      MapPublicIpOnLaunch: true  

  PubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CICDVPC

  PubRoute:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId: !Ref PubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  SubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubnet
      RouteTableId: !Ref PubRouteTable

  InstSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP & SSH access
      VpcId: !Ref CICDVPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-049a62eb90480f276 
      InstanceType: t2.micro
      KeyName: "ci-cd"
      SecurityGroupIds:
        - !Ref InstSecurityGroup
      SubnetId: !Ref PubSubnet
      Tags:
        - Key: Name
          Value: PipelineServer
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install nginx -y
          sudo systemctl start nginx          

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "DDCloud-Ranjith"

